name: Sync to GitLab

on:
  push:
    branches:
      - main   # change if needed

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # required for mirror


      - name: Debug environment
        run: |
          echo "🔍 Checking variables......."

          if [ -z "$G_TOKEN" ]; then
            echo "❌ G_TOKEN is EMPTY"
          else
            echo "✅ G_TOKEN is present"
            echo "🔑 Token length: ${#G_TOKEN}"
          fi

      - name: Mirror to GitLab
        run: |
          echo "🚀 Starting GitLab sync..."

          REPO_URL="https://mishraddeepak:${G_TOKEN}@gitlab.com/mishraddeepak/ddeepakmishra5-group/ddeepakmishra5-project.git"

          echo "📌 Target repo:"
          echo "$REPO_URL" | sed 's/:.*@/:****@/'   # mask token

          git remote add gitlab "$REPO_URL" || git remote set-url gitlab "$REPO_URL"

          echo "📡 Pushing mirror..."
          git push --mirror gitlab

          echo "✅ Sync completed"
        env:
          G_TOKEN: ${{ secrets.G_TOKEN }}
