name: Sync to GitLab

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        env:
          G_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git push --mirror https://mishraddeepak:${G_TOKEN}@://gitlab.com
